### ISSUE TITLE
 Cannot find module 'strapi-plugin-redirects'

### ISSUE THREAD

**Issue by bgrabbi** [Webbist-dev/strapi-redirects#1]
I have installed straps-plugin-redirect using
``` npm install strapi-plugin-redirects ```

and add 

```
redirects: {
    id: 'redirects',
    enabled: true,
    resolve: require('strapi-plugin-redirects'),
  },
````

I am getting below error.

``` Error: Could not load js config file ./config/plugins.js: ```

I also tried to delete .cache and node_modules
I also tried `yarn`

I tried with latest strapi version 4.10.0 and also with 4.4.3

**Comment by bgrabbi** [comment]
is this maintained @Webbist-dev ?

**Comment by eruiz-impact** [comment]
I am getting the same error.

**Comment by bskuratov** [comment]
I have faced the same problem. Solved it by switching the config to: 
```
 redirects: {
    enabled: true,
  },
```

**Comment by BL-Alex** [comment]
Maintained, yes - will update the readme!

**Comment by Webbist-dev** [comment]
I will update the readme. 

And yes, it's maintained.

**Comment by kurtisRogers-Nomensa** [comment]
Adding my 5 pence which will hopefully save someone an hour or so. If you're using docker for your Strapi app you will need to rebuild the app via `docker-compose build`. And then simply `docker-compose up -d <your_app_name>`.
