### ISSUE TITLE
The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by kubarazny** [Webbist-dev/strapi-redirects#11]
I got an error:

`error strapi-plugin-redirects@0.0.6: The engine "node" is incompatible with this module. Expected version ">=14.19.1 <= 18.x.x". Got "20.9.0"
error Found incompatible module.
`

will the plugin be updated?

**Comment by Webbist-dev** [comment]
Yes, update due soon (this week)

**Comment by Webbist-dev** [comment]
Fixed, sorry for the delay
