### ISSUE TITLE
0.0.7 Not published yet

### ISSUE THREAD

**Issue by alexgrauhanzo** [Webbist-dev/strapi-redirects#12]
In the repository i see that the last version of this plugin is 0.0.7 and a release has been made but i don't see it publish in npm neither in yarn. Is it plan to publish it soon?

**Comment by Webbist-dev** [comment]
Yeah apologies, been busy with work. 
I've rewritten the whole plugin, I'll publish it either today or tomorrow.
Need to run some final tests.

**Comment by colonder** [comment]
@Webbist-dev please do the update in your spare time, thanks in advance

**Comment by Webbist-dev** [comment]
Done, apologies for the delay - feedback is appreciated - as it's a total rewrite,
