### ISSUE TITLE
Unresolved peer dependency for Strapi 4.21.1 

### ISSUE THREAD

**Issue by chris-barklem** [Webbist-dev/strapi-redirects#16]
When using Strapi @
    "@strapi/strapi": "4.21.1",
With styled components installed by strapi:
    "styled-components": "^5.3.11"
The result is a unresolved peer dependency:

npm install strapi-plugin-redirects
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: strapi@0.1.0
npm ERR! Found: styled-components@5.3.11
npm ERR! node_modules/styled-components
npm ERR!   styled-components@"^5.3.11" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer styled-components@"5.3.3" from strapi-plugin-redirects@1.0.3
npm ERR! node_modules/strapi-plugin-redirects
npm ERR!   strapi-plugin-redirects@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 

I do not see in the readme of this project any indication of which versions of Strapi this plugin supports.

**Comment by Webbist-dev** [comment]
Patched in 1.0.4 and tested on 4.21.1 and 4.23.1 - peer dependency warning gone.
