### ISSUE TITLE
The page shows blank when click "Redirects" plugin

### ISSUE THREAD

**Issue by BuiPhuongThanh** [Webbist-dev/strapi-redirects#3]
When I clicked the "Redirects" plugin in admin page, it showed the blank page.
I see this error in console:

ReferenceError: Cannot access 'bi' before initialization
    at Module.default ([request].68174b71.chunk.js:139:101)

I tried on Strapi version 4.4.0, 4.4.5, 4.4.7.

**Comment by Webbist-dev** [comment]
I'll investigate

**Comment by BuiPhuongThanh** [comment]
> I'll investigate

Thank you. Do you face this problem in a test?

**Comment by Webbist-dev** [comment]
No issue in testing, a patch is coming out today - give it a try with the latest version
