### ISSUE TITLE
Minor naming issue concerning permanent/ temporary redirects

### ISSUE THREAD

**Issue by jasperhartong** [Webbist-dev/strapi-redirects#6]
Hi! Thanks for the plugin and including the setup example for Next.js.

A minor issue concerning the naming conventions in the Admin.

The type of redirects are indicated with the 301/ 302 status codes, although internally these are stored as "permanent"/ "temporary" and wil result in a 307/ 308 in Next.js. This might be confusing for editors.

Perhaps it would be better to just leave out the status codes in the admin?

**Comment by Webbist-dev** [comment]
I'll change the output in the admin to reflect the storage

**Comment by jasperhartong** [comment]
That sounds perfect!
