### ISSUE TITLE
Upgrade react to 18

### ISSUE THREAD

**Issue by michaltalaga** [Webbist-dev/strapi-redirects#7]
I have "@strapi/strapi": "4.14.0",
when I add this plugin I'm getting

_ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/client'_

Reason is strapi relies on "react": "^18.2.0", but this plugin puts "react": "^17.0.2", in node_modules

(same for "react-dom": "^17.0.2",)

for now I'm using this workaround

[package.json]

```
  "overrides": {
    "strapi-plugin-redirects": {
      "react": "^18.2.0",
      "react-dom": "^18.2.0"
    }
  },
```

**Comment by Webbist-dev** [comment]
I'll get this updated this weekend

**Comment by Webbist-dev** [comment]
Sorry for the delay
